import { spawn } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { config } from "../config.js";
import { log } from "../util/logger.js";

export interface ProveInputs {
  bids: bigint[]; // length == numSlots, zero-padded
  salts: bigint[]; // length == numSlots, zero-padded
  commitments: string[]; // 0x-prefixed hex, length == numSlots
  winnerIndex: number;
  secondPrice: bigint;
}

export interface ProveOutputs {
  proofHex: string; // 0x-prefixed
  publicInputs: string[]; // 0x-prefixed, each 32 bytes
  runDir: string;
}

function toFieldString(n: bigint): string {
  // Noir's Prover.toml accepts decimal strings for Field/integer types.
  return `"${n.toString(10)}"`;
}

function renderProverToml(inputs: ProveInputs): string {
  const { bids, salts, commitments, winnerIndex, secondPrice } = inputs;
  const bidsLine = `bids = [${bids.map(toFieldString).join(", ")}]`;
  const saltsLine = `salts = [${salts.map(toFieldString).join(", ")}]`;
  const commitmentsBlock =
    "commitments = [\n" +
    commitments.map((c, i) => `  "${c}"${i < commitments.length - 1 ? "," : ""}`).join("\n") +
    "\n]";
  return [
    "# Generated by zkbid backend at " + new Date().toISOString(),
    bidsLine,
    saltsLine,
    commitmentsBlock,
    `winner_index = "${winnerIndex}"`,
    `second_price = "${secondPrice.toString(10)}"`,
    "",
  ].join("\n");
}

function runProveScript(proverToml: string, proofDir: string): Promise<void> {
  return new Promise((resolve, reject) => {
    const script = path.join(config.circuitDir, "scripts", "prove.sh");
    if (!fs.existsSync(script)) {
      return reject(new Error(`prove.sh not found at ${script}`));
    }
    const child = spawn("bash", [script, proverToml, proofDir], {
      cwd: config.circuitDir,
      env: process.env,
      stdio: ["ignore", "pipe", "pipe"],
    });
    let stdout = "";
    let stderr = "";
    child.stdout.on("data", (d) => {
      const s = d.toString();
      stdout += s;
      log.info(`[prove] ${s.trimEnd()}`);
    });
    child.stderr.on("data", (d) => {
      const s = d.toString();
      stderr += s;
      log.warn(`[prove:stderr] ${s.trimEnd()}`);
    });
    child.on("error", (err) => reject(err));
    child.on("close", (code) => {
      if (code === 0) resolve();
      else reject(new Error(`prove.sh exited with code ${code}.\n${stderr || stdout}`));
    });
  });
}

function readBinaryAsHex(p: string): string {
  const buf = fs.readFileSync(p);
  return "0x" + buf.toString("hex");
}

function splitPublicInputs(publicInputsPath: string): string[] {
  const buf = fs.readFileSync(publicInputsPath);
  if (buf.length % 32 !== 0) {
    throw new Error(
      `public_inputs file ${publicInputsPath} length ${buf.length} is not a multiple of 32`,
    );
  }
  const out: string[] = [];
  for (let i = 0; i < buf.length; i += 32) {
    out.push("0x" + buf.subarray(i, i + 32).toString("hex"));
  }
  return out;
}

// Generates a proof for the given inputs. The prove.sh script is invoked with
// per-run paths so repeated /close calls don't clobber each other's outputs.
export async function generateProof(inputs: ProveInputs): Promise<ProveOutputs> {
  if (inputs.bids.length !== config.numSlots) {
    throw new Error(`expected ${config.numSlots} bids, got ${inputs.bids.length}`);
  }
  if (inputs.salts.length !== config.numSlots) {
    throw new Error(`expected ${config.numSlots} salts, got ${inputs.salts.length}`);
  }
  if (inputs.commitments.length !== config.numSlots) {
    throw new Error(`expected ${config.numSlots} commitments, got ${inputs.commitments.length}`);
  }

  const runId = new Date().toISOString().replace(/[:.]/g, "-");
  const runDir = path.join(config.dataDir, "runs", runId);
  const proofDir = path.join(runDir, "proof");
  fs.mkdirSync(proofDir, { recursive: true });

  const proverTomlPath = path.join(runDir, "Prover.toml");
  fs.writeFileSync(proverTomlPath, renderProverToml(inputs));
  log.info(`Wrote Prover.toml to ${proverTomlPath}`);

  log.info(`Running prove.sh (runId=${runId})...`);
  await runProveScript(proverTomlPath, proofDir);

  const proofPath = path.join(proofDir, "proof");
  const publicInputsPath = path.join(proofDir, "public_inputs");
  if (!fs.existsSync(proofPath)) {
    throw new Error(`proof file missing after prove.sh: ${proofPath}`);
  }
  if (!fs.existsSync(publicInputsPath)) {
    throw new Error(`public_inputs file missing after prove.sh: ${publicInputsPath}`);
  }

  const proofHex = readBinaryAsHex(proofPath);
  const publicInputs = splitPublicInputs(publicInputsPath);

  // Sanity: for 5 slots we expect 5 commitments + winner_index + second_price = 7
  const expectedLen = config.numSlots + 2;
  if (publicInputs.length !== expectedLen) {
    throw new Error(
      `public_inputs length mismatch: got ${publicInputs.length}, expected ${expectedLen}`,
    );
  }

  return { proofHex, publicInputs, runDir };
}
