export const AUCTION_ABI = [
  "function submitBid(uint256 slot, bytes32 commitment, bytes ephemeralPubkey, bytes nonce, bytes ciphertext) payable",
  "function finalize(uint256 winnerIndex, uint256 secondPrice, bytes proof)",
  "function withdraw()",
  "function phase() view returns (uint8)",
  "function commitDeadline() view returns (uint64)",
  "function minDeposit() view returns (uint256)",
  "function totalBids() view returns (uint256)",
  "function winnerIndex() view returns (uint256)",
  "function secondPrice() view returns (uint256)",
  "function seller() view returns (address)",
  "function auctioneer() view returns (address)",
  "function bidders(uint256) view returns (address)",
  "function deposits(uint256) view returns (uint256)",
  "function slotFilled(uint256) view returns (bool)",
  "function pendingWithdrawals(address) view returns (uint256)",
  "function getCommitments() view returns (bytes32[])",
  "function getEncryptedBid(uint256 slot) view returns (tuple(bytes ephemeralPubkey, bytes nonce, bytes ciphertext))",
  "event BidCommitted(uint256 indexed slot, address indexed bidder, bytes32 commitment, bytes ephemeralPubkey, bytes nonce, bytes ciphertext, uint256 deposit)",
  "event AuctionFinalized(uint256 indexed winnerIndex, address indexed winner, uint256 secondPrice)",
] as const;
